### ISSUE TITLE
diffusion enrichment with custom background metabolite set. 

### ISSUE THREAD

**Issue by RolandTengolics** [b2slab/FELLA#21]
Dear Developers!

I am very grateful for this nice tool. 
Please let me ask that, is it possible to run diffusion enrichment with custom background metabolite set?
When I am trying to run diffusion enrichment with using custom background metabolite set. 
Following code: 
analysis.nafld_3 <- enrich(
  compounds = cpd.nafld, # vector of significantly changed components 
  compoundsBackground = cpd.bckground, # vector of background components 
  data = fella.data) # generated from graph. 
  
I got error message the relevant part is this:
Running diffusion...
Computing p-scores through the specified distribution.
Diffusion matrix not loaded. Normality is not available for custom background without it.

Could you please give some advice how it is possible to overcome this issue? - How I can load / generate the diffusion matrix with custom background set? 

The hypergeometric test is working properly. 

Kind regards,
Roland Tengölics

**Comment by SergiPicart** [comment]
Dear Roland, thank you for your interest!

The `approx = "normality"` approximation (default in `enrich()`) uses pre-computed quantities that use by default all the metabolites in the graph. Custom backgrounds require computing those again. See the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/FELLA/inst/doc/FELLA.pdf). Then you have two options - let's assume you use the default `method = "diffusion"`:

1. If you want to keep using `approx = "normality"`, make sure you generate the diffusion matrix in `buildDataFromGraph()` by using `matrices = "diffusion"`, and that you load it with `loadMatrix = "diffusion"` in `loadKEGGdata()`
2. Use `approx = "simulation"` instead of `approx = "normality"`

Please let me know if that works

**Comment by RolandTengolics** [comment]
Dear Sergi,

I am grateful for your answer. Version 1 seems working, but is is giving a bit confusing result (pathway which is captured by only 2 metabolites directly). I am still studying how I can fine-tune  the calculations. 

Kind regards,
Roland

**Comment by SergiPicart** [comment]
Dear Roland,
Thank you for confirming the solution works; I am curious about the outcome of your fine-tuning. Closing the issue, please feel free to reopen if necessary.
Best, 
Sergi
