### ISSUE TITLE
Expand pathway databases

### ISSUE THREAD

**Issue by DeniseSl22** [b2slab/FELLA#22]
Dear developers, I was wondering if you are planning to extend you package with metabolic pathways from other databases (e.g. Reactome, WikiPathways)?

**Comment by SergiPicart** [comment]
Dear Denise, it is not in our immediate horizon to do so. 

We considered it, but their structure is not as straightforward as KEGG's hierarchy. One may create knowledge graphs for Reactome and/or WikiPathways, but some aspects may require iterative testing and entail decisions. For instance, the number of nodes (total and per category, degree of imbalance), need for node filtering, criteria to connect nodes, how to weigh edges. Since network propagation works in KEGG, I expect it to work for other dbs too, but maybe not off-the-shelf
