### ISSUE TITLE
buildGraphFromKEGGREST can't work

### ISSUE THREAD

**Issue by wuzeming** [b2slab/FELLA#23]
@nturaga 

Dear,

I appreciate your distinguished work published in BMC bioinformatics 2018. I can't agree with you more that metabolomics community must embrace new generation data mining philosophy for enrichment and get inslight about altered metabolic pathway.

but, i am facing trouble as shown below when i am trying your program. actually, I am a mass spectrometrist, and l know very limited about R programming. Could you help me to fix my problem, pls?
![image](https://user-images.githubusercontent.com/82150151/171381472-3b062f27-37e0-4128-8d81-bf52a0a700c4.png)

**Comment by nturaga** [comment]
Hi, 

Please send an email to bioc-devel@r-project.org if you have questions regarding Bioconductor.

**Comment by SergiPicart** [comment]
Dear Wuzeming,

Thank you for using FELLA. It looks like there are issues retrieving the files from the KEGG servers. Have you checked if a command like `KEGGREST::keggLink("cpd", "pathway")` works? (since FELLA uses KEGGREST under the hood). If it does not, you may check for general connectivity issues, like firewalls or proxies
Best,
Sergi

**Comment by wuzeming** [comment]
Dear Sergi,

thank your kindly reply. I tried your recommendation and the command  KEGGREST::keggLink("cpd", "pathway") still can't work. anyway, i will go to my webmaster to check the general connectivity of my workstation.
thanks again.

Best,
zeming
